root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "tailwindcss --minify -i ./templ/input.css -o ./assets/output.css && echo \"Tailwind Generated\" && sqlc generate && echo \"SQLc Generated\" && templ generate && echo \"Templ Generated\" && go build -o ./tmp/main . && echo \"Go Built\""
  delay = 1000
  exclude_dir = ["tmp", "db", "node_modules"]
  exclude_regex = [".*_templ.go", "output.css"]
  include_ext = ["go", "templ", "css", "sql", "env"]
  include_file = ["./tailwind.config.js"]
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true